name: Level Update

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Call API
        run: |
          curl --fail -i \
            -X POST \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
            https://knowlet.in/api/automation/level-update
